name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Get rsrc
        run: go get -u github.com/akavel/rsrc
      - name: Run rsrc
        run: $(go env GOPATH)/bin/rsrc -manifest manifest.xml -o manifest.syso
      - name: go mod tidy (this is needed after go get)
        run: go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
